apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api-server
  name: api-server
spec:
  containers:
  - env:
    - name: DATABASE_URL
      value: postgresql://postgres:itjustworks@local-db:5432/mydb
    - name: MODE
      value: local
    - name: PORT
      value: "8080"
    image: konamarsacrdemo.azurecr.io/lms-public-api:latest
    name: api-server
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}