apiVersion: v1
kind: Pod
metadata:
  name: lms-web-pod
  labels:
    component: web

spec:
  containers:
    - name: lms-web-container
      image: lms-web
      imagePullPolicy: Never
      ports:
        - containerPort: 80